name: Build, Analyze and Deploy Deliveries Microservice

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/deliveries-microservice:${{ github.sha }}

jobs:
  build:
    name: Build, Analyze and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar errores de prueba
        if: failure()
        run: cat deliveries/target/surefire-reports/*.txt || true
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build with Maven
        working-directory: deliveries
        run: mvn clean package

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Analyze with SonarCloud
        working-directory: deliveries
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=Carlos-Camacho2003_deliveries-microservice \
          -Dsonar.organization=carlos-camacho2003 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: deliveries
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Tag as latest and push
        run: |
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/deliveries-microservice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/deliveries-microservice:latest
